-- Run this SQL in your Supabase SQL Editor to create the market_leads table

CREATE TABLE IF NOT EXISTS market_leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url TEXT UNIQUE NOT NULL,
    name TEXT,
    company TEXT,
    source TEXT,
    date_found DATE,
    ai_score INTEGER,
    ai_summary TEXT,
    ai_notes TEXT,
    status TEXT DEFAULT 'New',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Index for faster URL lookups (deduplication)
CREATE INDEX IF NOT EXISTS idx_market_leads_url ON market_leads (url);

-- Index for filtering by score
CREATE INDEX IF NOT EXISTS idx_market_leads_ai_score ON market_leads (ai_score);
